language: php
sudo: false
addons:
  apt:
    packages:
    - poppler-utils
php:
  - 7.2
before_script:
 - composer install -vvv
 - bash tests/travis-setup.sh
script:
 - phpunit -c phpunit.xml
after_success:
 - travis_retry php vendor/bin/coveralls
